version: '2'
services:
    imageupload-app:
        image: imageupload
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://imageupload-mysql:3306/imageupload?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8585:8585
    imageupload-mysql:
        extends:
            file: mysql.yml
            service: imageupload-mysql
